Repository team-yeo-eun-pa/greenFire-backend, pull requests merged in 2024-06, with the labels that each got.

#51 #50 관리자 회원관리 조회 기능 개선
  src/main/java/yep/greenFire/greenfirebackend/admin/member/service/AdminMemberService.java
Labels: 😎개선

#58 #54 ExceptionCode 분류 유형 수정
  src/main/java/yep/greenFire/greenfirebackend/common/exception/type/ExceptionCode.java
Labels: 🚥test, 🔨refactor

#73 #72 상품 목록 조회 수정
  src/main/java/yep/greenFire/greenfirebackend/auth/config/SecurityConfig.java
  src/main/java/yep/greenFire/greenfirebackend/order/service/OrderService.java
  src/main/java/yep/greenFire/greenfirebackend/product/domain/entity/Product.java
  src/main/java/yep/greenFire/greenfirebackend/product/domain/entity/ProductOption.java
  src/main/java/yep/greenFire/greenfirebackend/product/domain/repository/ProductRepository.java
  src/main/java/yep/greenFire/greenfirebackend/product/domain/type/SellableStatus.java
  src/main/java/yep/greenFire/greenfirebackend/product/dto/response/ProductOptionResponse.java
  src/main/java/yep/greenFire/greenfirebackend/product/dto/response/ProductResponse.java
  src/main/java/yep/greenFire/greenfirebackend/product/dto/response/ProductsResponse.java
  src/main/java/yep/greenFire/greenfirebackend/product/presentation/ProductController.java
  src/main/java/yep/greenFire/greenfirebackend/product/service/ProductService.java
  src/main/resources/static/productimg/0fe54e3b76374c0b808a702857a57240.png
Labels: 🔨refactor

#76 #69 스토어 신고하기, 회원 신고하기, 관리자 신고조회, 상세조회 수정
  settings.gradle
  src/main/java/yep/greenFire/greenfirebackend/member/domain/repository/MemberRepository.java
  src/main/java/yep/greenFire/greenfirebackend/order/service/OrderService.java
  src/main/java/yep/greenFire/greenfirebackend/product/dto/response/ProductsResponse.java
  src/main/java/yep/greenFire/greenfirebackend/report/domain/repository/ReportRepository.java
  src/main/java/yep/greenFire/greenfirebackend/report/dto/request/ReportCreateRequest.java
  src/main/java/yep/greenFire/greenfirebackend/report/dto/response/ReportsVO.java
  src/main/java/yep/greenFire/greenfirebackend/report/presentation/ReportController.java
  src/main/java/yep/greenFire/greenfirebackend/report/presentation/ReportMemberController.java
  src/main/java/yep/greenFire/greenfirebackend/report/service/ReportMemberService.java
  src/main/java/yep/greenFire/greenfirebackend/report/service/ReportService.java
  src/main/java/yep/greenFire/greenfirebackend/seller/service/StoreService.java
  src/main/java/yep/greenFire/greenfirebackend/store/domain/entity/Store.java
  src/main/java/yep/greenFire/greenfirebackend/store/domain/repository/StoreRepository.java
Labels: 🌱feat, 🔨refactor

#77 #52 결제 기능 구현
  build.gradle
  src/main/java/yep/greenFire/greenfirebackend/order/domain/entity/Order.java
  src/main/java/yep/greenFire/greenfirebackend/order/service/OrderService.java
  src/main/java/yep/greenFire/greenfirebackend/payment/domain/entity/Payment.java
  src/main/java/yep/greenFire/greenfirebackend/payment/domain/repository/PaymentRepository.java
  src/main/java/yep/greenFire/greenfirebackend/payment/domain/type/PaymentStatus.java
  src/main/java/yep/greenFire/greenfirebackend/payment/domain/type/PaymentWay.java
  src/main/java/yep/greenFire/greenfirebackend/payment/dto/request/PaymentCreateRequest.java
  src/main/java/yep/greenFire/greenfirebackend/payment/dto/request/PaymentRequest.java
  src/main/java/yep/greenFire/greenfirebackend/payment/presentation/PaymentController.java
  src/main/java/yep/greenFire/greenfirebackend/payment/presentation/WidgetController.java
  src/main/java/yep/greenFire/greenfirebackend/payment/service/PaymentService.java
Labels: 🌱feat

#82 #81 쿠폰 디렉토리 변경
  src/main/java/yep/greenFire/greenfirebackend/coupon/domain/entity/Coupon.java
  src/main/java/yep/greenFire/greenfirebackend/coupon/domain/entity/CouponCreation.java
  src/main/java/yep/greenFire/greenfirebackend/coupon/domain/entity/CouponProduct.java
  src/main/java/yep/greenFire/greenfirebackend/coupon/domain/type/CouponStatus.java
Labels: 🔨refactor

#86 [Refactor] 회원 공지사항 조회 및 상세조회
  src/main/java/yep/greenFire/greenfirebackend/auth/config/SecurityConfig.java
  src/main/java/yep/greenFire/greenfirebackend/notice/dto/response/MemberNoticeResponse.java
  src/main/java/yep/greenFire/greenfirebackend/notice/dto/response/MemberNoticesResponse.java
  src/main/java/yep/greenFire/greenfirebackend/notice/presentation/MemberNoticeController.java
  src/main/java/yep/greenFire/greenfirebackend/notice/presentation/NoticeController.java
  src/main/java/yep/greenFire/greenfirebackend/notice/service/MemberNoticeService.java
Labels: 🔨refactor

#88 [Refactor] 회원 신고하기
  src/main/java/yep/greenFire/greenfirebackend/report/dto/request/ReportCreateRequest.java
  src/main/java/yep/greenFire/greenfirebackend/report/presentation/ReportController.java
Labels: 🔨refactor

#89 #66 관리자 신규 입점 신청 조회/상세조회/승인/거절
  src/main/java/yep/greenFire/greenfirebackend/apply/domain/repository/ApplyRepository.java
  src/main/java/yep/greenFire/greenfirebackend/apply/dto/request/ApplyUpdateRequest.java
  src/main/java/yep/greenFire/greenfirebackend/apply/dto/response/AdminApplyResponse.java
  src/main/java/yep/greenFire/greenfirebackend/apply/presentation/AdminApplyController.java
  src/main/java/yep/greenFire/greenfirebackend/apply/service/ApplyService.java
  src/main/java/yep/greenFire/greenfirebackend/common/exception/type/ExceptionCode.java
  src/main/java/yep/greenFire/greenfirebackend/seller/domain/entity/Seller.java
Labels: 🌱feat

#92 #90 마이페이지 / 마이스토어 수정 기능 및 조회 리팩토링
  src/main/java/yep/greenFire/greenfirebackend/common/exception/type/ExceptionCode.java
  src/main/java/yep/greenFire/greenfirebackend/member/domain/entity/Member.java
  src/main/java/yep/greenFire/greenfirebackend/member/dto/request/ProfileUpdateRequest.java
  src/main/java/yep/greenFire/greenfirebackend/member/presentation/MemberController.java
  src/main/java/yep/greenFire/greenfirebackend/member/service/MemberService.java
  src/main/java/yep/greenFire/greenfirebackend/seller/domain/entity/Seller.java
  src/main/java/yep/greenFire/greenfirebackend/seller/domain/repository/SellerRepository.java
  src/main/java/yep/greenFire/greenfirebackend/seller/dto/response/StoreProfileResponse.java
  src/main/java/yep/greenFire/greenfirebackend/seller/presentation/SellerController.java
  src/main/java/yep/greenFire/greenfirebackend/seller/service/SellerService.java
  src/main/java/yep/greenFire/greenfirebackend/store/domain/entity/Store.java
  src/main/java/yep/greenFire/greenfirebackend/store/domain/repository/StoreRepository.java
  src/main/java/yep/greenFire/greenfirebackend/store/dto/request/StoreProfileUpdateRequest.java
  src/main/java/yep/greenFire/greenfirebackend/store/dto/response/StoreListResponse.java
  src/main/java/yep/greenFire/greenfirebackend/store/dto/response/StoreProfileResponse.java
  src/main/java/yep/greenFire/greenfirebackend/store/presentation/StoreController.java
  src/main/java/yep/greenFire/greenfirebackend/store/service/StoreService.java
Labels: 🌱feat, 🔨refactor

#95 #94 관리자 정지회원 조회 기능 수정
  src/main/java/yep/greenFire/greenfirebackend/member/domain/repository/MemberRepository.java
  src/main/java/yep/greenFire/greenfirebackend/member/presentation/AdminMemberController.java
  src/main/java/yep/greenFire/greenfirebackend/notice/dto/request/NoticeCreateRequest.java
  src/main/java/yep/greenFire/greenfirebackend/notice/presentation/NoticeController.java
  src/main/java/yep/greenFire/greenfirebackend/notice/service/NoticeService.java
  src/main/java/yep/greenFire/greenfirebackend/report/domain/repository/ReportRepository.java
  src/main/java/yep/greenFire/greenfirebackend/report/presentation/ReportMembersController.java
  src/main/java/yep/greenFire/greenfirebackend/report/service/ReportMembersService.java
  src/main/java/yep/greenFire/greenfirebackend/seller/service/StoreService.java
Labels: 🔨refactor

#98 [Refactor] @JsonFormat 추가
  src/main/java/yep/greenFire/greenfirebackend/member/domain/entity/Member.java
  src/main/java/yep/greenFire/greenfirebackend/member/dto/response/MemberResponse.java
  src/main/java/yep/greenFire/greenfirebackend/notice/domain/entity/Notice.java
  src/main/java/yep/greenFire/greenfirebackend/notice/dto/response/AdminNoticeResponse.java
  src/main/java/yep/greenFire/greenfirebackend/notice/dto/response/AdminNoticesResponse.java
  src/main/java/yep/greenFire/greenfirebackend/report/dto/response/ReportsVO.java
Labels: 🔨refactor

#102 #101 결제 취소 기본 세팅
  http/order-test.http
  http/payment-test.http
  src/main/java/yep/greenFire/greenfirebackend/order/domain/entity/Order.java
  src/main/java/yep/greenFire/greenfirebackend/order/domain/entity/StoreOrder.java
  src/main/java/yep/greenFire/greenfirebackend/order/domain/repository/OrderRepository.java
  src/main/java/yep/greenFire/greenfirebackend/order/domain/type/OrderStatus.java
  src/main/java/yep/greenFire/greenfirebackend/order/dto/response/OrderDetailDTO.java
  src/main/java/yep/greenFire/greenfirebackend/order/dto/response/OrderResponse.java
  src/main/java/yep/greenFire/greenfirebackend/order/dto/response/StoreOrderDTO.java
  src/main/java/yep/greenFire/greenfirebackend/order/presentation/OrderController.java
  src/main/java/yep/greenFire/greenfirebackend/order/service/OrderService.java
  src/main/java/yep/greenFire/greenfirebackend/payment/config/MvcConfiguration.java
  src/main/java/yep/greenFire/greenfirebackend/payment/domain/entity/Payment.java
  src/main/java/yep/greenFire/greenfirebackend/payment/domain/entity/PaymentCancel.java
  src/main/java/yep/greenFire/greenfirebackend/payment/domain/type/CancelStatus.java
  src/main/java/yep/greenFire/greenfirebackend/payment/domain/type/PaymentWay.java
  src/main/java/yep/greenFire/greenfirebackend/payment/dto/request/PaymentCancelRequest.java
  src/main/java/yep/greenFire/greenfirebackend/payment/presentation/PaymentController.java
  src/main/java/yep/greenFire/greenfirebackend/payment/service/PaymentService.java
  src/main/java/yep/greenFire/greenfirebackend/product/domain/entity/Product.java
Labels: 🌱feat

#106 #65 #66 신규 입점 관련 기능 보완
  src/main/java/yep/greenFire/greenfirebackend/apply/domain/repository/ApplyRepository.java
  src/main/java/yep/greenFire/greenfirebackend/apply/presentation/AdminApplyController.java
  src/main/java/yep/greenFire/greenfirebackend/apply/presentation/ApplyController.java
  src/main/java/yep/greenFire/greenfirebackend/apply/service/ApplyService.java
Labels: 🌱feat, 🔨refactor

#107 #103 판매자 주문 승인, 거절 기능 구현
  http/order-test.http
  http/seller-test.http
  src/main/java/yep/greenFire/greenfirebackend/order/domain/entity/Order.java
  src/main/java/yep/greenFire/greenfirebackend/order/domain/entity/StoreOrder.java
  src/main/java/yep/greenFire/greenfirebackend/order/domain/repository/OrderRepository.java
  src/main/java/yep/greenFire/greenfirebackend/order/domain/type/OrderStatus.java
  src/main/java/yep/greenFire/greenfirebackend/order/dto/request/OrderApprovalRequest.java
  src/main/java/yep/greenFire/greenfirebackend/order/presentation/OrderController.java
  src/main/java/yep/greenFire/greenfirebackend/order/service/OrderService.java
  src/main/java/yep/greenFire/greenfirebackend/store/domain/entity/Store.java
  src/main/java/yep/greenFire/greenfirebackend/store/dto/request/StoreProfileUpdateRequest.java
  src/main/java/yep/greenFire/greenfirebackend/store/dto/response/StoreProfileResponse.java
Labels: 🌱feat

#110 #109 관리자 공지사항 등록을 위한 리팩터
  src/main/java/yep/greenFire/greenfirebackend/notice/domain/entity/Notice.java
  src/main/java/yep/greenFire/greenfirebackend/notice/dto/request/NoticeCreateRequest.java
  src/main/java/yep/greenFire/greenfirebackend/notice/dto/response/AdminNoticesResponse.java
  src/main/java/yep/greenFire/greenfirebackend/notice/presentation/NoticeController.java
  src/main/java/yep/greenFire/greenfirebackend/notice/service/NoticeService.java
  src/main/java/yep/greenFire/greenfirebackend/order/domain/entity/Order.java
  src/main/java/yep/greenFire/greenfirebackend/order/service/OrderService.java
  src/main/java/yep/greenFire/greenfirebackend/product/dto/request/CategoryUpdateRequest.java
  src/main/java/yep/greenFire/greenfirebackend/store/domain/entity/Store.java
  src/main/java/yep/greenFire/greenfirebackend/store/dto/request/StoreProfileUpdateRequest.java
  src/main/java/yep/greenFire/greenfirebackend/store/dto/response/StoreProfileResponse.java
Labels: 🔨refactor

#111 #108 회원 배송지 CRUD 및 판매자 배송 처리 기능 구현
  http/order-test.http
  src/main/java/yep/greenFire/greenfirebackend/common/exception/type/ExceptionCode.java
  src/main/java/yep/greenFire/greenfirebackend/delivery/domain/entity/Delivery.java
  src/main/java/yep/greenFire/greenfirebackend/delivery/domain/entity/DeliveryAddress.java
  src/main/java/yep/greenFire/greenfirebackend/delivery/domain/repository/DeliveryAddressRepository.java
  src/main/java/yep/greenFire/greenfirebackend/delivery/domain/repository/DeliveryRepository.java
  src/main/java/yep/greenFire/greenfirebackend/delivery/domain/type/AddressType.java
  src/main/java/yep/greenFire/greenfirebackend/delivery/domain/type/DeliveryStatus.java
  src/main/java/yep/greenFire/greenfirebackend/delivery/domain/type/DeliveryType.java
  src/main/java/yep/greenFire/greenfirebackend/delivery/dto/request/DeliveryAddressRequest.java
  src/main/java/yep/greenFire/greenfirebackend/delivery/dto/response/DeliveryAddressResponse.java
  src/main/java/yep/greenFire/greenfirebackend/delivery/presentation/DeliveryController.java
  src/main/java/yep/greenFire/greenfirebackend/delivery/service/DeliveryService.java
  src/main/java/yep/greenFire/greenfirebackend/order/domain/entity/DeliveryAddress.java
  src/main/java/yep/greenFire/greenfirebackend/order/domain/type/AddressType.java
  src/main/java/yep/greenFire/greenfirebackend/order/dto/request/OrderApprovalRequest.java
  src/main/java/yep/greenFire/greenfirebackend/order/dto/request/OrderCreateRequest.java
  src/main/java/yep/greenFire/greenfirebackend/order/dto/response/OrderDetailDTO.java
  src/main/java/yep/greenFire/greenfirebackend/order/dto/response/OrderResponse.java
  src/main/java/yep/greenFire/greenfirebackend/order/dto/response/StoreOrderDTO.java
  src/main/java/yep/greenFire/greenfirebackend/order/presentation/OrderController.java
  src/main/java/yep/greenFire/greenfirebackend/order/service/OrderService.java
Labels: 🌱feat

#113 #112 기본 주소 타입
  src/main/java/yep/greenFire/greenfirebackend/order/domain/entity/Order.java
  src/main/java/yep/greenFire/greenfirebackend/order/domain/repository/DeliveryAddressRepository.java
  src/main/java/yep/greenFire/greenfirebackend/order/service/OrderService.java
  src/main/java/yep/greenFire/greenfirebackend/seller/domain/repository/Test.java
  src/main/java/yep/greenFire/greenfirebackend/seller/domain/type/AddressType.java
  src/main/java/yep/greenFire/greenfirebackend/seller/presentation/Test.java
  src/main/java/yep/greenFire/greenfirebackend/store/domain/entity/Store.java
  src/main/java/yep/greenFire/greenfirebackend/store/dto/request/StoreProfileUpdateRequest.java
  src/main/java/yep/greenFire/greenfirebackend/store/dto/response/StoreProfileResponse.java
  src/test/java/yep/greenfirebackend/GreenFireBackendApplicationTests.java
Labels: 🔨refactor

#114 #105 회원 문의 조회 디버깅
  src/main/java/yep/greenFire/greenfirebackend/inquiry/entity/InquiryContent.java
  src/main/java/yep/greenFire/greenfirebackend/inquiry/site/domain/repository/SiteInquiryRepository.java
  src/main/java/yep/greenFire/greenfirebackend/inquiry/site/dto/request/InquiryCreateRequest.java
  src/main/java/yep/greenFire/greenfirebackend/inquiry/site/dto/response/InquiryCreateResponse.java
  src/main/java/yep/greenFire/greenfirebackend/inquiry/site/dto/response/InquiryResponse.java
  src/main/java/yep/greenFire/greenfirebackend/inquiry/site/presentation/SiteInquiryController.java
  src/main/java/yep/greenFire/greenfirebackend/inquiry/site/service/SiteInquiryService.java
Labels: 🐞bug

#119 #118 회원 문의 상세조회
  http/inquiry/member-inquiry-viewDetail.http
  http/member-test.http
  src/main/java/yep/greenFire/greenfirebackend/inquiry/entity/InquiryContent.java
  src/main/java/yep/greenFire/greenfirebackend/inquiry/site/domain/repository/SiteInquiryRepository.java
  src/main/java/yep/greenFire/greenfirebackend/inquiry/site/dto/response/InquiryResponse.java
  src/main/java/yep/greenFire/greenfirebackend/inquiry/site/presentation/SiteInquiryController.java
  src/main/java/yep/greenFire/greenfirebackend/inquiry/site/service/SiteInquiryService.java
  src/main/java/yep/greenFire/greenfirebackend/order/dto/request/OrderApprovalRequest.java
Labels: 🌱feat

#120 #100 판매자 스토어 정보 수정 / 신규 등록 / 운영 정지
  src/main/java/yep/greenFire/greenfirebackend/apply/presentation/AdminApplyController.java
  src/main/java/yep/greenFire/greenfirebackend/order/domain/repository/OrderRepository.java
  src/main/java/yep/greenFire/greenfirebackend/store/domain/entity/Store.java
  src/main/java/yep/greenFire/greenfirebackend/store/domain/repository/StoreRepository.java
  src/main/java/yep/greenFire/greenfirebackend/store/domain/type/StoreStatus.java
  src/main/java/yep/greenFire/greenfirebackend/store/dto/request/StoreCloseRequest.java
  src/main/java/yep/greenFire/greenfirebackend/store/dto/response/StoreProfileResponse.java
  src/main/java/yep/greenFire/greenfirebackend/store/presentation/StoreController.java
  src/main/java/yep/greenFire/greenfirebackend/store/service/StoreService.java
Labels: 🌱feat, 🔨refactor

#122 #116 상품 상세 조회
  src/main/java/yep/greenFire/greenfirebackend/order/dto/request/OrderApprovalRequest.java
  src/main/java/yep/greenFire/greenfirebackend/product/domain/entity/Product.java
  src/main/java/yep/greenFire/greenfirebackend/product/domain/entity/ProductOption.java
  src/main/java/yep/greenFire/greenfirebackend/product/domain/repository/ProductOptionRepository.java
  src/main/java/yep/greenFire/greenfirebackend/product/domain/repository/ProductRepository.java
  src/main/java/yep/greenFire/greenfirebackend/product/dto/ProductDTO.java
  src/main/java/yep/greenFire/greenfirebackend/product/dto/ProductOptionDTO.java
  src/main/java/yep/greenFire/greenfirebackend/product/dto/response/ProductResponse.java
  src/main/java/yep/greenFire/greenfirebackend/product/presentation/ProductController.java
  src/main/java/yep/greenFire/greenfirebackend/product/service/ProductService.java
Labels: 🌱feat

#126 #121 회원가입 이메일 본인인증
  build.gradle
  src/main/java/yep/greenFire/greenfirebackend/auth/config/SchedulerConfig.java
  src/main/java/yep/greenFire/greenfirebackend/auth/config/SecurityConfig.java
  src/main/java/yep/greenFire/greenfirebackend/auth/dto/Test.java
  src/main/java/yep/greenFire/greenfirebackend/auth/presentaition/AuthController.java
  src/main/java/yep/greenFire/greenfirebackend/email/domain/entity/EmailVerification.java
  src/main/java/yep/greenFire/greenfirebackend/email/domain/repository/EmailVerificationRepository.java
  src/main/java/yep/greenFire/greenfirebackend/email/dto/request/VerificationRequest.java
  src/main/java/yep/greenFire/greenfirebackend/email/service/EmailService.java
  src/main/java/yep/greenFire/greenfirebackend/email/service/EmailVerificationCleanupService.java
  src/main/java/yep/greenFire/greenfirebackend/email/service/EmailVerificationService.java
  src/main/java/yep/greenFire/greenfirebackend/member/domain/entity/Member.java
  src/main/java/yep/greenFire/greenfirebackend/member/domain/type/MemberStatus.java
  src/main/java/yep/greenFire/greenfirebackend/member/dto/request/MemberSignupRequest.java
  src/main/java/yep/greenFire/greenfirebackend/member/presentation/MemberController.java
  src/main/java/yep/greenFire/greenfirebackend/member/service/MemberService.java
Labels: ⚙set, 🌱feat

#125 #124 리뷰 조회
  http/member-test.http
  src/main/java/yep/greenFire/greenfirebackend/challenge/domain/entity/Challenge.java
  src/main/java/yep/greenFire/greenfirebackend/challenge/domain/entity/ChallengeContent.java
  src/main/java/yep/greenFire/greenfirebackend/challenge/domain/repository/ChallengeRepository.java
  src/main/java/yep/greenFire/greenfirebackend/challenge/domain/type/ChallengeStatus.java
  src/main/java/yep/greenFire/greenfirebackend/challenge/dto/response/ChallengeResponse.java
  src/main/java/yep/greenFire/greenfirebackend/challenge/dto/response/ChallengesResponse.java
  src/main/java/yep/greenFire/greenfirebackend/challenge/dto/response/challenge/ChallengeResponse.java
  src/main/java/yep/greenFire/greenfirebackend/challenge/presentation/ChallengeController.java
  src/main/java/yep/greenFire/greenfirebackend/challenge/service/ChallengeService.java
  src/main/java/yep/greenFire/greenfirebackend/notice/domain/entity/Notice.java
  src/main/java/yep/greenFire/greenfirebackend/review/domain/entity/Review.java
  src/main/java/yep/greenFire/greenfirebackend/review/domain/repository/ReviewRepository.java
  src/main/java/yep/greenFire/greenfirebackend/review/domain/type/ReviewReplyStatus.java
  src/main/java/yep/greenFire/greenfirebackend/review/domain/type/ReviewStatus.java
  src/main/java/yep/greenFire/greenfirebackend/review/dto/response/ReviewResponse.java
  src/main/java/yep/greenFire/greenfirebackend/review/presentation/ReviewController.java
  src/main/java/yep/greenFire/greenfirebackend/review/service/ReviewService.java
Labels: 🌱feat

#130 #129 상품 리뷰 상세조회
  src/main/java/yep/greenFire/greenfirebackend/auth/presentaition/AuthController.java
  src/main/java/yep/greenFire/greenfirebackend/email/service/EmailService.java
  src/main/java/yep/greenFire/greenfirebackend/email/service/EmailVerificationService.java
  src/main/java/yep/greenFire/greenfirebackend/member/presentation/MemberController.java
  src/main/java/yep/greenFire/greenfirebackend/order/domain/entity/OrderDetail.java
  src/main/java/yep/greenFire/greenfirebackend/review/domain/entity/Review.java
  src/main/java/yep/greenFire/greenfirebackend/review/domain/repository/ReviewRepository.java
  src/main/java/yep/greenFire/greenfirebackend/review/dto/request/ReviewRequest.java
  src/main/java/yep/greenFire/greenfirebackend/review/dto/response/ReviewResponse.java
  src/main/java/yep/greenFire/greenfirebackend/review/presentation/ReviewController.java
  src/main/java/yep/greenFire/greenfirebackend/review/service/ReviewService.java
Labels: 🔨refactor

#131 #121 회원가입 이메일 본인인증 플로우 수정
  src/main/java/yep/greenFire/greenfirebackend/auth/config/SecurityConfig.java
  src/main/java/yep/greenFire/greenfirebackend/auth/presentaition/AuthController.java
  src/main/java/yep/greenFire/greenfirebackend/email/service/EmailService.java
  src/main/java/yep/greenFire/greenfirebackend/email/service/EmailVerificationService.java
  src/main/java/yep/greenFire/greenfirebackend/member/presentation/MemberController.java
Labels: 🌱feat, 🔨refactor

#137 #67 회원 판매자 권한 병합
  src/main/java/yep/greenFire/greenfirebackend/auth/config/SecurityConfig.java
Labels: 🌱feat

#139 #100 운영 정지 기능 개선
  src/main/java/yep/greenFire/greenfirebackend/auth/handler/LoginSuccessHandler.java
  src/main/java/yep/greenFire/greenfirebackend/common/exception/type/ExceptionCode.java
  src/main/java/yep/greenFire/greenfirebackend/order/domain/repository/StoreOrderRepositoryCustomImpl.java
  src/main/java/yep/greenFire/greenfirebackend/store/presentation/StoreController.java
  src/main/java/yep/greenFire/greenfirebackend/store/service/StoreService.java
Labels: 🌱feat, 🔨refactor

#140 #118 문의 상세보기 구현
  src/main/java/yep/greenFire/greenfirebackend/inquiry/site/domain/repository/SiteInquiryRepository.java
  src/main/java/yep/greenFire/greenfirebackend/inquiry/site/presentation/SiteInquiryController.java
  src/main/java/yep/greenFire/greenfirebackend/inquiry/site/service/SiteInquiryService.java
Labels: 🌱feat

#144 #118 문의 상세보기
  src/main/java/yep/greenFire/greenfirebackend/common/exception/type/ExceptionCode.java
  src/main/java/yep/greenFire/greenfirebackend/inquiry/site/domain/repository/SiteInquiryRepository.java
  src/main/java/yep/greenFire/greenfirebackend/inquiry/site/dto/response/InquiryResponse.java
  src/main/java/yep/greenFire/greenfirebackend/inquiry/site/presentation/SiteInquiryController.java
  src/main/java/yep/greenFire/greenfirebackend/inquiry/site/service/SiteInquiryService.java
Labels: 🌱feat

#145 #142 이미지 조회 수정
  src/main/java/yep/greenFire/greenfirebackend/auth/config/SecurityConfig.java
  src/main/java/yep/greenFire/greenfirebackend/member/presentation/MemberController.java
  src/main/java/yep/greenFire/greenfirebackend/order/domain/repository/OrderDetailRepositoryCustomImpl.java
  src/main/java/yep/greenFire/greenfirebackend/order/presentation/OrderController.java
  src/main/java/yep/greenFire/greenfirebackend/product/domain/entity/Product.java
  src/main/java/yep/greenFire/greenfirebackend/product/dto/ProductDTO.java
  src/main/java/yep/greenFire/greenfirebackend/product/dto/response/ProductsResponse.java
  src/main/java/yep/greenFire/greenfirebackend/product/dto/response/SellerProductsResponse.java
  src/main/java/yep/greenFire/greenfirebackend/product/presentation/ProductController.java
  src/main/java/yep/greenFire/greenfirebackend/product/service/ProductService.java
Labels: 🔨refactor

#147 #146 상품 관리 기능 수정
  http/cart-test.http
  http/product-test.http
  src/main/java/yep/greenFire/greenfirebackend/product/domain/entity/ProductOption.java
  src/main/java/yep/greenFire/greenfirebackend/product/domain/repository/ProductOptionRepository.java
  src/main/java/yep/greenFire/greenfirebackend/product/presentation/ProductController.java
  src/main/java/yep/greenFire/greenfirebackend/product/service/ProductOptionService.java
  src/main/java/yep/greenFire/greenfirebackend/product/service/ProductService.java
Labels: 🔨refactor

#150 #149 주문 등록 리턴 값 변경 및 배송지 엔터티 추가
  http/order-test.http
  src/main/java/yep/greenFire/greenfirebackend/common/exception/type/ExceptionCode.java
  src/main/java/yep/greenFire/greenfirebackend/delivery/dto/response/DeliveryAddressResponse.java
  src/main/java/yep/greenFire/greenfirebackend/order/domain/entity/Order.java
  src/main/java/yep/greenFire/greenfirebackend/order/domain/entity/OrderDetail.java
  src/main/java/yep/greenFire/greenfirebackend/order/domain/repository/OrderRepositoryCustomImpl.java
  src/main/java/yep/greenFire/greenfirebackend/order/domain/repository/StoreOrderRepositoryCustomImpl.java
  src/main/java/yep/greenFire/greenfirebackend/order/domain/type/OrderStatus.java
  src/main/java/yep/greenFire/greenfirebackend/order/dto/response/OrderResponse.java
  src/main/java/yep/greenFire/greenfirebackend/order/presentation/OrderController.java
  src/main/java/yep/greenFire/greenfirebackend/order/service/OrderService.java
  src/main/java/yep/greenFire/greenfirebackend/payment/presentation/PaymentController.java
  src/main/java/yep/greenFire/greenfirebackend/payment/service/PaymentService.java
Labels: 🔨refactor

#148 #123 장바구니 기능 구현
  src/main/java/yep/greenFire/greenfirebackend/cart/domain/entity/Cart.java
  src/main/java/yep/greenFire/greenfirebackend/cart/domain/repository/CartRepository.java
  src/main/java/yep/greenFire/greenfirebackend/cart/dto/request/CartItemRequest.java
  src/main/java/yep/greenFire/greenfirebackend/cart/dto/response/CartItemResponse.java
  src/main/java/yep/greenFire/greenfirebackend/cart/presentation/CartController.java
  src/main/java/yep/greenFire/greenfirebackend/cart/service/CartService.java
  src/main/java/yep/greenFire/greenfirebackend/common/exception/type/ExceptionCode.java
  src/main/java/yep/greenFire/greenfirebackend/product/dto/request/ProductOptionRequest.java
Labels: 🌱feat

#152 #151 상품 옵션 버그 수정
  src/main/java/yep/greenFire/greenfirebackend/product/dto/request/ProductOptionRequest.java
Labels: 🐞bug
