Repository team-yeo-eun-pa/greenFire-backend, pull requests merged in 2024-05, with the labels that each got.

#4 #1 admin notice view
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/domain/entity/Member.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/domain/entity/Notice.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/domain/repository/NoticeRepository.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/domain/type/NoticeStatusType.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/dto/response/AdminNoticesResponse.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/presentation/NoticeController.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/service/NoticeService.java
  src/main/java/yep/greenFire/greenfirebackend/common/paging/Pagination.java
  src/main/java/yep/greenFire/greenfirebackend/common/paging/PagingButtonInfo.java
  src/main/java/yep/greenFire/greenfirebackend/common/paging/PagingResponse.java
  src/main/java/yep/greenFire/greenfirebackend/common/paging/Test.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ✨기능

#7 #2 member regist
  http/member-test.http
  src/main/java/yep/greenFire/greenfirebackend/GreenFireBackendApplication.java
  src/main/java/yep/greenFire/greenfirebackend/auth/config/BeanConfig.java
  src/main/java/yep/greenFire/greenfirebackend/auth/config/SecurityConfig.java
  src/main/java/yep/greenFire/greenfirebackend/auth/service/AuthService.java
  src/main/java/yep/greenFire/greenfirebackend/user/member/domain/entity/Member.java
  src/main/java/yep/greenFire/greenfirebackend/user/member/domain/entity/Test.java
  src/main/java/yep/greenFire/greenfirebackend/user/member/domain/repository/MemberRepository.java
  src/main/java/yep/greenFire/greenfirebackend/user/member/domain/repository/Test.java
  src/main/java/yep/greenFire/greenfirebackend/user/member/domain/type/MemberRole.java
  src/main/java/yep/greenFire/greenfirebackend/user/member/domain/type/MemberStatus.java
  src/main/java/yep/greenFire/greenfirebackend/user/member/dto/request/MemberSignupRequest.java
  src/main/java/yep/greenFire/greenfirebackend/user/member/dto/request/Test.java
  src/main/java/yep/greenFire/greenfirebackend/user/member/presentation/MemberController.java
  src/main/java/yep/greenFire/greenfirebackend/user/member/presentation/Test.java
  src/main/java/yep/greenFire/greenfirebackend/user/member/service/MemberService.java
  src/main/java/yep/greenFire/greenfirebackend/user/member/service/Test.java
  src/main/resources/application.yml
Labels: ✨기능

#9 Feature/#1 관리자 공지사항 상세조회
  build.gradle
  http/admin-test.http
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/domain/entity/AdminMember.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/domain/entity/Notice.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/domain/repository/NoticeRepository.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/dto/request/NoticeCreateRequest.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/dto/response/AdminNoticeResponse.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/presentation/NoticeController.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/service/NoticeService.java
  src/main/java/yep/greenFire/greenfirebackend/auth/config/SecurityConfig.java
  src/main/java/yep/greenFire/greenfirebackend/common/exception/ConflictException.java
  src/main/java/yep/greenFire/greenfirebackend/common/exception/CustomException.java
  src/main/java/yep/greenFire/greenfirebackend/common/exception/NotFoundException.java
  src/main/java/yep/greenFire/greenfirebackend/common/exception/ServerInternalException.java
  src/main/java/yep/greenFire/greenfirebackend/common/exception/dto/response/ExceptionResponse.java
  src/main/java/yep/greenFire/greenfirebackend/common/exception/dto/response/Test.java
  src/main/java/yep/greenFire/greenfirebackend/common/exception/handler/ExceptionHandlingController.java
  src/main/java/yep/greenFire/greenfirebackend/common/exception/handler/Test.java
  src/main/java/yep/greenFire/greenfirebackend/common/exception/type/ExceptionCode.java
  src/main/java/yep/greenFire/greenfirebackend/common/exception/type/Test.java
  src/main/resources/application.yml
Labels: ✨기능

#10 [#8] 로그인 기능 구현
  build.gradle
  http/member-test.http
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/domain/entity/Notice.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/domain/entity/NoticeMember.java
  src/main/java/yep/greenFire/greenfirebackend/auth/config/SecurityConfig.java
  src/main/java/yep/greenFire/greenfirebackend/auth/config/Test.java
  src/main/java/yep/greenFire/greenfirebackend/auth/dto/LoginDTO.java
  src/main/java/yep/greenFire/greenfirebackend/auth/dto/TokenDTO.java
  src/main/java/yep/greenFire/greenfirebackend/auth/filter/CustomAuthenticationFilter.java
  src/main/java/yep/greenFire/greenfirebackend/auth/filter/JwtAuthenticationFilter.java
  src/main/java/yep/greenFire/greenfirebackend/auth/filter/Test.java
  src/main/java/yep/greenFire/greenfirebackend/auth/handler/JwtAccessDeniedHandler.java
  src/main/java/yep/greenFire/greenfirebackend/auth/handler/JwtAuthenticationEntryPoint.java
  src/main/java/yep/greenFire/greenfirebackend/auth/handler/LoginFailureHandler.java
  src/main/java/yep/greenFire/greenfirebackend/auth/handler/LoginSuccessHandler.java
  src/main/java/yep/greenFire/greenfirebackend/auth/handler/Test.java
  src/main/java/yep/greenFire/greenfirebackend/auth/service/AuthService.java
  src/main/java/yep/greenFire/greenfirebackend/auth/type/CustomUser.java
  src/main/java/yep/greenFire/greenfirebackend/auth/type/Test.java
  src/main/java/yep/greenFire/greenfirebackend/auth/util/Test.java
  src/main/java/yep/greenFire/greenfirebackend/auth/util/TokenUtils.java
  src/main/java/yep/greenFire/greenfirebackend/common/exception/NotFoundException.java
  src/main/java/yep/greenFire/greenfirebackend/common/exception/dto/response/ExceptionResponse.java
  src/main/java/yep/greenFire/greenfirebackend/common/exception/handler/ExceptionHandlingController.java
  src/main/java/yep/greenFire/greenfirebackend/user/member/domain/entity/Member.java
  src/main/java/yep/greenFire/greenfirebackend/user/member/domain/repository/MemberRepository.java
  src/main/java/yep/greenFire/greenfirebackend/user/member/presentation/MemberController.java
  src/main/java/yep/greenFire/greenfirebackend/user/member/service/MemberService.java
Labels: ✨기능, 🚥테스트

#11 #1 관리자 공지사항 crud 끝
  http/admin-test.http
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/domain/entity/AdminMember.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/domain/entity/Notice.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/domain/repository/AdminMemberRepository.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/domain/repository/NoticeRepository.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/domain/type/NoticeStatusType.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/dto/request/NoticeCreateRequest.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/dto/request/NoticeUpdateRequest.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/dto/response/AdminMemberResponse.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/dto/response/AdminNoticeResponse.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/dto/response/AdminNoticesResponse.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/presentation/AdminMemberController.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/presentation/NoticeController.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/service/AdminMemberService.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/service/NoticeService.java
  src/main/java/yep/greenFire/greenfirebackend/auth/config/SecurityConfig.java
  src/main/java/yep/greenFire/greenfirebackend/common/exception/type/ExceptionCode.java
Labels: ✨기능

#17 #13 관리자 카테고리 기능 완성
  http/admin-test.http
  http/member-test.http
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/domain/entity/AdminMember.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/domain/entity/Category.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/domain/entity/NoticeMember.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/domain/repository/CategoryRepository.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/domain/repository/NoticeRepository.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/dto/request/CategoryCreateRequest.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/dto/request/CategoryUpdateRequest.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/dto/response/AdminCategoryResponse.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/dto/response/MemberNoticeResponse.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/presentation/CategoryController.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/presentation/NoticeController.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/service/CategoryService.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/service/NoticeService.java
  src/main/java/yep/greenFire/greenfirebackend/auth/config/SecurityConfig.java
  src/main/java/yep/greenFire/greenfirebackend/common/exception/type/ExceptionCode.java
Labels: ✨기능

#16 #12 회원 공지사항 조회, 상세조회
  http/admin-test.http
  http/member-test.http
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/domain/entity/NoticeMember.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/domain/repository/NoticeRepository.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/dto/response/MemberNoticeResponse.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/presentation/NoticeController.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/service/NoticeService.java
  src/main/java/yep/greenFire/greenfirebackend/auth/config/SecurityConfig.java
Labels: ✨기능

#20 #18 주문 등록 기능 구현
  src/main/java/yep/greenFire/greenfirebackend/common/exception/type/ExceptionCode.java
  src/main/java/yep/greenFire/greenfirebackend/order/domain/entity/DeliveryAddress.java
  src/main/java/yep/greenFire/greenfirebackend/order/domain/entity/Order.java
  src/main/java/yep/greenFire/greenfirebackend/order/domain/entity/OrderDetail.java
  src/main/java/yep/greenFire/greenfirebackend/order/domain/entity/StoreOrder.java
  src/main/java/yep/greenFire/greenfirebackend/order/domain/repository/DeliveryAddressRepository.java
  src/main/java/yep/greenFire/greenfirebackend/order/domain/repository/OrderRepository.java
  src/main/java/yep/greenFire/greenfirebackend/order/domain/type/OrderStatus.java
  src/main/java/yep/greenFire/greenfirebackend/order/dto/request/OrderCreateRequest.java
  src/main/java/yep/greenFire/greenfirebackend/order/presentation/OrderController.java
  src/main/java/yep/greenFire/greenfirebackend/order/service/OrderService.java
  src/main/java/yep/greenFire/greenfirebackend/product/domain/entity/ProductOption.java
  src/main/java/yep/greenFire/greenfirebackend/product/domain/entity/Test.java
  src/main/java/yep/greenFire/greenfirebackend/product/domain/repository/ProductOptionRepository.java
  src/main/java/yep/greenFire/greenfirebackend/product/domain/repository/Test.java
  src/main/java/yep/greenFire/greenfirebackend/product/domain/type/ProductOptionAppearActivate.java
  src/main/java/yep/greenFire/greenfirebackend/product/domain/type/Test.java
  src/main/java/yep/greenFire/greenfirebackend/product/service/ProductOptionService.java
  src/main/java/yep/greenFire/greenfirebackend/product/service/Test.java
Labels: ✨기능

#22 #14 회원 프로필 조회 기능 구현
  http/member-test.http
  src/main/java/yep/greenFire/greenfirebackend/user/member/dto/request/MemberSignupRequest.java
  src/main/java/yep/greenFire/greenfirebackend/user/member/dto/response/ProfileResponse.java
  src/main/java/yep/greenFire/greenfirebackend/user/member/dto/response/Test.java
  src/main/java/yep/greenFire/greenfirebackend/user/member/presentation/MemberController.java
  src/main/java/yep/greenFire/greenfirebackend/user/member/service/MemberService.java
Labels: ✨기능

#26 #25 로그아웃 기능 구현
  http/member-test.http
  src/main/java/yep/greenFire/greenfirebackend/user/member/presentation/MemberController.java
Labels: ✨기능

#28 #15 문의게시판 회원:조회/등록/상세조회 구현
  http/inquiry-test.http
  src/main/java/yep/greenFire/greenfirebackend/auth/service/AuthService.java
  src/main/java/yep/greenFire/greenfirebackend/challenge/domain/entity/InquiryContent.java
  src/main/java/yep/greenFire/greenfirebackend/challenge/domain/entity/Test.java
  src/main/java/yep/greenFire/greenfirebackend/challenge/domain/repository/InquiryRepository.java
  src/main/java/yep/greenFire/greenfirebackend/challenge/domain/repository/Test.java
  src/main/java/yep/greenFire/greenfirebackend/challenge/dto/request/AdminCsCreateRequest.java
  src/main/java/yep/greenFire/greenfirebackend/challenge/dto/request/InquiryCreateRequest.java
  src/main/java/yep/greenFire/greenfirebackend/challenge/dto/request/Test.java
  src/main/java/yep/greenFire/greenfirebackend/challenge/dto/response/AdminInquiryDetailResponse.java
  src/main/java/yep/greenFire/greenfirebackend/challenge/dto/response/AdminInquiryResponse.java
  src/main/java/yep/greenFire/greenfirebackend/challenge/dto/response/InquiryOneResponse.java
  src/main/java/yep/greenFire/greenfirebackend/challenge/dto/response/InquiryResponse.java
  src/main/java/yep/greenFire/greenfirebackend/challenge/dto/response/Test.java
  src/main/java/yep/greenFire/greenfirebackend/challenge/presentation/InquiryController.java
  src/main/java/yep/greenFire/greenfirebackend/challenge/presentation/Test.java
  src/main/java/yep/greenFire/greenfirebackend/challenge/service/InquiryService.java
  src/main/java/yep/greenFire/greenfirebackend/challenge/service/Test.java
  src/main/java/yep/greenFire/greenfirebackend/common/exception/type/ExceptionCode.java
Labels: ✨기능

#30 #19 관리자 신고관리 기능 (회원) 끝
  http/member-test.http
  src/main/java/yep/greenFire/greenfirebackend/admin/category/presentation/CategoryController.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/presentation/NoticeController.java
  src/main/java/yep/greenFire/greenfirebackend/admin/report/presentation/ReportMemberController.java
  src/main/java/yep/greenFire/greenfirebackend/admin/report/presentation/ReportMembersController.java
  src/main/java/yep/greenFire/greenfirebackend/admin/report/presentation/SuspensionOverController.java
  src/main/java/yep/greenFire/greenfirebackend/admin/report/service/ReportMemberService.java
  src/main/java/yep/greenFire/greenfirebackend/admin/report/service/ReportMembersService.java
  src/main/java/yep/greenFire/greenfirebackend/admin/report/service/SuspenseOverService.java
  src/main/java/yep/greenFire/greenfirebackend/challenge/domain/type/Test.java
  src/main/java/yep/greenFire/greenfirebackend/common/exception/type/ExceptionCode.java
  src/main/java/yep/greenFire/greenfirebackend/user/member/domain/entity/Member.java
  src/main/java/yep/greenFire/greenfirebackend/user/member/domain/repository/MemberRepository.java
  src/main/java/yep/greenFire/greenfirebackend/user/member/service/MemberService.java
  src/main/java/yep/greenFire/greenfirebackend/user/report/domain/entity/Report.java
  src/main/java/yep/greenFire/greenfirebackend/user/report/domain/repository/ReportRepository.java
  src/main/java/yep/greenFire/greenfirebackend/user/report/presentation/ReportController.java
  src/main/java/yep/greenFire/greenfirebackend/user/review/domain/entity/Review.java
Labels: ✨기능

#33 #32 CICD 수정
  src/main/java/yep/greenFire/greenfirebackend/challenge/domain/entity/Comment.java
Labels: 🐞버그

#35 #34 signup login fix
  http/member-test.http
  src/main/java/yep/greenFire/greenfirebackend/admin/report/presentation/SuspensionOverController.java
  src/main/java/yep/greenFire/greenfirebackend/user/member/domain/entity/Member.java
  src/main/java/yep/greenFire/greenfirebackend/user/member/dto/request/MemberSignupRequest.java
  src/main/java/yep/greenFire/greenfirebackend/user/member/dto/response/MemberResponse.java
  src/main/java/yep/greenFire/greenfirebackend/user/member/service/MemberService.java
  src/main/java/yep/greenFire/greenfirebackend/user/report/presentation/ReportController.java
  src/main/java/yep/greenFire/greenfirebackend/user/report/service/ReportService.java
Labels: 🐞버그

#46 #45 관리자 공지사항 조회와 상세조회
  http/admin-test.http
  http/member-test.http
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/domain/repository/NoticeRepository.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/dto/request/NoticeCreateRequest.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/dto/response/AdminNoticeResponse.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/dto/response/AdminNoticesResponse.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/presentation/NoticeController.java
  src/main/java/yep/greenFire/greenfirebackend/admin/notice/service/NoticeService.java
  src/main/java/yep/greenFire/greenfirebackend/admin/report/presentation/SuspensionOverController.java
  src/main/java/yep/greenFire/greenfirebackend/user/member/domain/entity/Member.java
  src/main/java/yep/greenFire/greenfirebackend/user/member/service/MemberService.java
  src/main/java/yep/greenFire/greenfirebackend/user/notice/service/MemberNoticeService.java
  src/main/java/yep/greenFire/greenfirebackend/user/report/presentation/ReportController.java
  src/main/java/yep/greenFire/greenfirebackend/user/report/service/ReportService.java
Labels: 😎개선

#49 #48 상품 옵션 타입 변경
  http/order-test.http
  src/main/java/yep/greenFire/greenfirebackend/product/domain/entity/ProductOption.java
  src/main/java/yep/greenFire/greenfirebackend/product/domain/type/ProductOptionAppearActivate.java
  src/main/java/yep/greenFire/greenfirebackend/product/service/ProductOptionService.java
Labels: 🐞버그
